jQuery(document).ready(function($) {
    $('.product-slider').slick({
    //     dots: false,
    //     infinite: true,
    //     slidesToShow: 1,
    //     prevArrow: false,
    //     nextArrow: false,
    //     autoplay: true,
    //     autoplaySpeed: 3000,
    //     speed: 3000,
    //     centerMode:true,
    //     adaptiveHeight: true,
    //     initialSlide: 1,
    // centerPadding: '0px',  
    slidesToShow: 1,
    slidesToScroll: 1,
    adaptiveHeight:true,
    prevArrow:false,
    nextArrow:false,
    // autoplay:true,
    dots: false,
    infinite: false,
        autoplaySpeed: 3000,
        speed: 3000,
    });
    $('.hero-image-slider').slick({
        dots: false,
        infinite: true,
        slidesToShow: 1,
        prevArrow: false,
        nextArrow: false,
        autoplay: true,
        autoplaySpeed: 1500,
        speed: 1500,
        centerMode:false,  
        adaptiveHeight: true,
    });
});
